apiVersion: v1
kind: Service
metadata:
  name: playlist
  namespace: bookify
spec:
  selector:
    app: playlist
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 50053
      targetPort: 50053
