apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: bookify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: bookify_mine-reviews
          imagePullPolicy: Never   # ðŸ‘ˆ OBLIGATORIO para KIND
          ports:
            - containerPort: 8082   # HTTP
            - containerPort: 50052  
            
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "userbookify"
            - name: DB_PASSWORD
              value: "user_bookify"
            - name: DB_NAME
              value: "bookify"
            - name: DB_PORT
              value: "5432"
