apiVersion: v1
kind: Service
metadata:
  name: shelves
  namespace: bookify
spec:
  selector:
    app: shelves
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 50055
      targetPort: 50055
